env:
  PORT: 80
  ROOT_URL: http://192.168.2.240:80
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/qhd-beta
    objectFiles:
     - ./objects/**
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
  webservices:
    workflow:
      url: "http://127.0.0.1/"