env:
  PORT: 6000
  ROOT_URL: http://127.0.0.1:6000
datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/qhd-beta
public:
  cfs:
    store: "local"
    local:
      folder: "/storage"
  webservices:
    workflow:
      url: "http://127.0.0.1/"